export { default as Landing } from "../pages/Landing/LandingPage"
export { default as PersonalInfo } from "../pages/InfoLaptop/PersonalInfo"
export { default as LaptopInfo } from "../pages/InfoLaptop/LaptopInfo"
export { default as Modal } from "../pages/Modal/Modal"
export { default as EntriesList } from "../pages/EntriesList/EntriesList"
export { default as InfoPage } from "../pages/InfoPage/InfoPage"